### PR TITLE
Portoflio mobile page

### PR DESCRIPTION
**Pull request by Haywayaheadshot**
## What?
 Mobile phone menu page for my portoflio.

## Why?
To serve as a landing page for users.

## How?
Recreated template 1 of the mobile menu options given by Microverse using flexbox.

### CODE REVIEW

**Review by codecaiine — COMMENTED** [review]
Hi @Haywayaheadshot , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that node_modules folder is in the repo and is not in the .gitignore file so i is not ignored by git. And I also encourage you to always use initial PR for all re-reviews.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Haywayaheadshot** [comment]
@codecaiine I had it in the src folder because I thought it could be in any folder. But I just read that it has to be in the root folder. 

Instead of "node_modules" can I use "node_modules/"?

**Comment by codecaiine** [comment]
Hi @Haywayaheadshot I think your project structure is also a problem. I would like to recommend you have a structure like the one in the screenshot below. Your dist and src folder is useless for this module. It s makes it confusing like you are working on webpack project but it s just an HTML and CSS project. 
 
Screenshot from 2022-08-18 16-18-51

**Comment by codecaiine** [comment]
If you need any help please tag me again or slack me .

**Comment by Haywayaheadshot** [comment]
@codecaiine I have made the changes as you mentioned. Could you please take a minute to check before I submit it?

**Comment by codecaiine** [comment]
Hi @Haywayaheadshot I'm leaving you a message on slack. Please let us slack :+1:

**Comment by Haywayaheadshot** [comment]
@codecaiine I did not realize my slack app was not on. I am on now

**Review by topeogunleye — COMMENTED** [review]
Hi @Haywayaheadshot, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a project that has failing linters, Kindly make sure your linters are all passing before submitting the PR.

## Stlylint AutoFix
- [ ] if you have a lot of CSS line errors, I kindly suggest you fix them with `npx stylelint --fix "**/*.{css,scss}"`, but please get used to fixing the errors line by line also because it'll help you learn best practices.

## Gitflow Not Used ⚠️

- Pull request is to be made from the feature branch into the dev branch not main branch.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Review by mwanawabangona — APPROVED** [review]
Hi @Haywayaheadshot,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  


## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
