### PR TITLE
Validation of form

### PR DESCRIPTION
**Pull request by Haywayaheadshot**
## What?

I validated forms to allow the correct form of an email.

## Why?

This is to allow me get the correct contact information of interested users so as to keep a good customer relationship.

## How?

> I created a regular expression that only allows the condition of lower case letters, an @ symbol, and no white spaces between the email.
> I created a div and set the display to none in HTML right under the "Get In Touch" button.
> I created an event listener for the submit button to check for the regular expression and alert the user on how to correctly format their email and allow them to submit their form if the email is formatted correctly.

### CODE REVIEW

**Review by Ismailco — COMMENTED** [review]
Hi @Haywayaheadshot, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that should be created using peer-programming, all the students on the group should commit to this PR

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Haywayaheadshot** [comment]
Thank you for the review @Ismailco but I no longer have a coding partner. I am alone in my coding group

**Review by roshan-bajgain — COMMENTED** [review]
Hi @Haywayaheadshot, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that you did solo but this is pair programming. please do it with your partner and we will see the commit history for confirmation.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Ismailco** [comment]
I didn't know that, it would be helpful to mention this in your PR so the reviewer know the situation

**Comment by Haywayaheadshot** [comment]
> 

This is my mistake. I added it in “Additional information section on the submission instead. I will include in the PR”

Thank you

**Review by Kamba56 — APPROVED** [review]
Hi @Haywayaheadshot, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [x] Great use of Github flow
- [x] All linters passed
- [ ] Great commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Haywayaheadshot** [comment]
Thank you @Kamba56

**Pull request merged**
